apiVersion: v1
kind: Service              
metadata:
  name: kub-front-lb
spec:
  type: LoadBalancer       
  ports:
  - port: 80               
    protocol: TCP          
    targetPort: 80         
  selector:                
    app: kub-front       