apiVersion: v1
kind: Service              
metadata:
  name: kub-auth
spec:
  type: LoadBalancer       
  ports:
  - port: 8081              
    protocol: TCP          
    targetPort: 8081         
  selector:                
    app: kub-auth       