apiVersion: v1
kind: Service              
metadata:
  name: kub-res-lb
spec:
  type: LoadBalancer       
  ports:
  - port: 8085              
    protocol: TCP          
    targetPort: 8085         
  selector:                
    app: kub-res       